[project]
name = "chapter1"
version = "0.1.0"
description = "Chapter 1: The Learning Problem"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
]
